export const continentToCountries: Record<string, string[]> = {
  africa: [
    "Nigeria",
    "South Africa",
    "Egypt",
    "Kenya",
    "Ghana",
    "Morocco",
    "Algeria",
    "Tanzania",
    "Uganda",
    "Angola",
    "Ethiopia",
    "Zimbabwe",
    "Zambia",
    "Mauritius",
    "Namibia",
    "Botswana",
    "Mozambique",
    "Liberia",
    "Sierra Leone",
    "Senegal",
    "Mali",
    "Burkina Faso",
    "Ivory Coast",
    "Niger",
    "Gabon",
    "Central African Republic",
    "South Sudan",
    "Eritrea",
    "Somalia",
    "Djibouti",
    "Comoros",
    "Sao Tome and Principe",
    "Lesotho",
    "Swaziland",
    "Equatorial Guinea",
    "Guinea-Bissau",
    "Guinea",
    "Cape Verde",
    "Madagascar",
    "Seychelles",
    "Chad",
    "Cameroon",
    "Republic of the Congo",
    "Democratic Republic of the Congo",
    "Rwanda",
    "Burundi",
    "Tunisia",
    "Libya",
    "Western Sahara",
    "Benin",
    "Togo",
    "Gambia",
    "Mauritania",
    "Malawi",
    "Sudan",
  ],
  asia: [
    "China",
    "India",
    "Japan",
    "South Korea",
    "Indonesia",
    "Pakistan",
    "Bangladesh",
    "Vietnam",
    "Thailand",
    "Malaysia",
    "Singapore",
    "Philippines",
    "Myanmar",
    "Cambodia",
    "Laos",
    "Nepal",
    "Sri Lanka",
    "Maldives",
    "Afghanistan",
    "Iran",
    "Iraq",
    "Saudi Arabia",
    "United Arab Emirates",
    "Israel",
    "Jordan",
    "Lebanon",
    "Syria",
    "Yemen",
    "Oman",
    "Kuwait",
    "Bahrain",
    "Qatar",
    "Georgia",
    "Armenia",
    "Azerbaijan",
    "Kazakhstan",
    "Uzbekistan",
    "Turkmenistan",
    "Kyrgyzstan",
    "Tajikistan",
    "North Korea",
    "Mongolia",
    "Bhutan",
    "Brunei",
    "Timor-Leste",
    "UAE",
    "Palest",
    "Taiwan",
    "Hong Kong",
    "Macau",
    "Tibet",
  ],
  europe: [
    "UK",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "United Kingdom",
    "Netherlands",
    "Portugal",
    "Belgium",
    "Switzerland",
    "Austria",
    "Sweden",
    "Norway",
    "Denmark",
    "Finland",
    "Ireland",
    "Greece",
    "Turkey",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Romania",
    "Bulgaria",
    "Serbia",
    "Croatia",
    "Slovakia",
    "Slovenia",
    "Estonia",
    "Latvia",
    "Lithuania",
    "Belarus",
    "Ukraine",
    "Moldova",
    "Georgia",
    "Armenia",
    "Azerbaijan",
    "Monaco",
    "San Marino",
    "Andorra",
    "Liechtenstein",
    "Vatican City",
    "Luxembourg",
    "Malta",
    "Iceland",
    "Faroe Islands",
    "Greenland",
    "Isle of MAN",
  ],
  northAmerica: [
    "United States",
    "USA",
    "Canada",
    "Mexico",
    "Guatemala",
    "Honduras",
    "El Salvador",
    "Nicaragua",
    "Costa Rica",
    "Panama",
    "Cuba",
    "Dominican Republic",
    "Haiti",
    "Jamaica",
    "Trinidad and Tobago",
    "Barbados",
    "Saint Lucia",
    "Grenada",
    "Saint Vincent and the Grenadines",
    "Antigua and Barbuda",
    "Saint Kitts and Nevis",
    "Belize",
    "Bahamas",
    "Bermuda",
    "Cayman Islands",
    "Saint Pierre and Miquelon",
    "US",
  ],
  southAmerica: [
    "Brazil",
    "Argentina",
    "Colombia",
    "Chile",
    "Peru",
    "Venezuela",
    "Ecuador",
    "Bolivia",
    "Paraguay",
    "Uruguay",
    "Guyana",
    "Suriname",
    "French Guiana",
    "Falkland Islands",
  ],
  oceania: [
    "Australia",
    "New Zealand",
    "Fiji",
    "Papua New Guinea",
    "Solomon Islands",
    "Vanuatu",
    "Samoa",
    "Tonga",
    "Kiribati",
    "Tuvalu",
    "Nauru",
    "Marshall Islands",
    "Palau",
    "Micronesia",
    "Northern Mariana Islands",
    "American Samoa",
    "French Polynesia",
    "New Caledonia",
    "Wallis and Futuna",
    "Cook Islands",
    "Niue",
    "Tokelau",
    "Pitcairn Islands",
    "Guam",
  ],
};
